<?php
/**
 * @file
 * Module file for miniOrange SAML Module.
 */
 
/**
* Implements hook_menu().
*/
use Drupal\miniorange_saml_idp\Utilities;
use Drupal\miniorange_saml_idp\MiniOrangeAuthnRequest;
use Drupal\miniorange_saml_idp\XMLSecurityKey;
use Drupal\miniorange_saml_idp\Controller\miniorange_saml_idpController;

function miniorange_saml_idp_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'miniorange_saml_idp/miniorange_saml_idp.admin';
}

function miniorange_saml_idp_user_login($account){
 
 
  if(isset($_COOKIE['response_params'])){
   
    $response_params =  json_decode(stripslashes($_COOKIE['response_params']),true);
    if(strcmp( $response_params['moIdpsendResponse'], 'true') == 0) {
	  $control = new miniorange_saml_idpController();
      $control->mo_idp_send_reponse($response_params['acs_url'],$response_params['audience'],$response_params['relayState'],$response_params['inResponseTo']);
    }
  }
}

